---
chromebook: true

# utils
tmux_conf:
  history_limit: 1000
  has_xsel: true
  has_firefox: false
dotfiles:
  - bashrc
  - gitconfig
  - tmux.conf
  - xinitrc
  - Xmodmap

# vim
vim_plugins_github:
  - gmarik/Vundle.vim
  - godlygeek/tabular
  - itchyny/lightline.vim
  - ctrlpvim/ctrlp.vim
  - rking/ag.vim
  - scrooloose/nerdcommenter
  - tpope/vim-fugitive
  - tpope/vim-surround
  - vim-scripts/Tagbar
