---
dns_forwarders:
  # opendns
  - 208.67.222.222
  - 208.67.220.220
  # google
  - 8.8.8.8
  - 8.8.4.4
dns_acl:
  name: trusted
  matches:
    - localnets
dns_zone_dir: /etc/named/zones
dns_domain: alkali
dns_a_records:
  192.168.1.1:
    - router
    - siebnes
  192.168.1.8:
    - iphone
  192.168.1.21:
    - iridium
  192.168.1.67:
    - bismuth
  192.168.1.91:
    - chrome
  192.168.1.187:
    - cerium
  192.168.1.191:
    - oxygen
  192.168.1.223:
    - helium
    - git
