---
custom_blacklist:
 - 33across.com
 - ads.investingchannel.com
 - ads.pubmatic.com
 - asset.pagefair.com
 - cxsense.com
 - fusion.di.se
 - insplanet.se
 - native.sharethrough.com
 - richmetrics.com
