---
ansible_host: 192.168.84.3
ansible_python_interpreter: /usr/bin/python2

vim_plugins_github:
  - godlygeek/tabular
  - itchyny/lightline.vim
  - ctrlpvim/ctrlp.vim
  - mattn/emmet-vim
  - rking/ag.vim
  - scrooloose/nerdcommenter
  - tpope/vim-fugitive
  - tpope/vim-surround
  - vim-scripts/Tagbar
